### ISSUE TITLE
Домашка №1, HTML

### ISSUE THREAD

**Issue by tiny-kottan** [abatovua/kottansHW#2]
Разметить эту страницу: https://habrahabr.ru/post/244929/
от вас ожидаеться `.html` файл с семантичной разметкой, без css/js
крупные части контента копипастить не стоит (саму статью, там `h*`/`p`/`code` -- все просто), а вот остальное -- нужно
как должно выглядить
```html
<!doctype html>
<html lang=ru>
<meta charset=utf-8>
<title>Habrahabr.ru</title>
<header>
  <ul>
    <li><a href=...>TM Feed</a>
    <li><a>Хабрахабр</a>
  </ul>```

**Comment by abatovua** [comment]
https://github.com/abatovua/kottansHW/tree/master/1week/topic%20markup

**Comment by mkozhukharenko** [comment]
dont use aside as a wrapper
https://github.com/abatovua/kottansHW/blob/master/1week/topic%20markup/index.html#L8

https://github.com/vrd/kottans-js-2016/issues/2#issuecomment-221067829:
>  Aside is not a sidebar or wrapper for random stuff - it's container for secondary(secondary to main article or website)!

**Comment by mkozhukharenko** [comment]
https://github.com/abatovua/kottansHW/blob/master/1week/topic%20markup/index.html#L48-L54 this shouldn't be inside a nav
Could you read few articles about a `nav` element and make a short list of argument why that element should/shouldn't be a `nav`, please?  e.g. [this chapter](http://html5doctor.com/avoiding-common-html5-mistakes/#nav-external)

**Comment by mkozhukharenko** [comment]
I would make an author name (`@rayproud`) as a `figcaption`.
https://github.com/abatovua/kottansHW/blob/master/1week/topic%20markup/index.html#L58-L64

**Comment by mkozhukharenko** [comment]
it isn't a progress, for sure https://github.com/abatovua/kottansHW/blob/master/1week/topic%20markup/index.html#L70

**Comment by mkozhukharenko** [comment]
`main` should wrap a main article as well. What do you think about this?

**Comment by mkozhukharenko** [comment]
It isn't an article, isnt' it? 
https://github.com/abatovua/kottansHW/blob/master/1week/topic%20markup/index.html#L123
https://github.com/abatovua/kottansHW/blob/master/1week/topic%20markup/index.html#L159

read [this](http://html5doctor.com/the-article-element/) to get more info

**Comment by mkozhukharenko** [comment]
can it be a `nav` ? https://github.com/abatovua/kottansHW/blob/master/1week/topic%20markup/index.html#L255-L256
what do you think?

**Comment by abatovua** [comment]
> dont use aside as a wrapper
https://github.com/abatovua/kottansHW/blob/master/1week/topic%20markup/index.html#L8

> vrd/kottans-js-2016#2 (comment):

> Aside is not a sidebar or wrapper for random stuff - it's container for secondary(secondary to main article or website)!
don't use a section as a wrapper (if it has not semantic meaning)
https://github.com/abatovua/kottansHW/blob/master/1week/topic%20markup/index.html#L206

I put an aside cause block contains only links to related resources and projects. So it's secondary for the whole website.

Comments block is section cause set of articles(comments) has meaning only in conjunction.

**Comment by abatovua** [comment]
< https://github.com/abatovua/kottansHW/blob/master/1week/topic%20markup/index.html#L48-L54 this shouldn't be inside a nav
Could you read few articles about a nav element and make a short list of argument why that element should/shouldn't be a nav, please? e.g. this chapter

**Comment by abatovua** [comment]
> I would make an author name (@rayproud) as a figcaption.
https://github.com/abatovua/kottansHW/blob/master/1week/topic%20markup/index.html#L58-L64

Fixed.

**Comment by abatovua** [comment]
> it isn't a progress, for sure https://github.com/abatovua/kottansHW/blob/master/1week/topic%20markup/index.html#L70

Changed to meter.

**Comment by abatovua** [comment]
> main should wrap a main article as well. What do you think about this? https://github.com/abatovua/kottansHW/blob/master/1week/topic%20markup/index.html#L106

don't really understand what do you mean. It's already contain it.

**Comment by abatovua** [comment]
> It isn't an article, isnt' it? 
https://github.com/abatovua/kottansHW/blob/master/1week/topic%20markup/index.html#L123
https://github.com/abatovua/kottansHW/blob/master/1week/topic%20markup/index.html#L159

read this to get more info

It's my fault for sure. But i was definataly sure that it's article after our lection. Misunderstanding. According to given article i guess it's section and simple block. Fixed.

**Comment by abatovua** [comment]
> can it be a nav ? https://github.com/abatovua/kottansHW/blob/master/1week/topic%20markup/index.html#L255-L256
what do you think?

It shouldn't be a nav:
* it's not the main navigation
* it's not contain links within the current page
* it's located in footer with other tons of small(styles) links

So i guess it small list of links in footer

**Comment by mkozhukharenko** [comment]
> I put an aside cause block contains only links to related resources and projects. So it's secondary for the whole website.

> Comments block is section cause set of articles(comments) has meaning only in conjunction.

It will be better to have: 
```html
    <div class="wrapper">
      <aside>
        <ul>
          <li><a href="/tmfeed">TM Feed</a></li>
          <li><a href="/habr">Хабрахабр</a></li>
          <li><a href="/geek">Geektimes</a></li>
          <li><a href="/toster">Тостер</a></li>
          <li><a href="/mycircle">Мой круг</a></li>
          <li><a href="/freelance">Фрилансим</a></li>
        </ul>
      </aside>
      <aside>
        <h1>Спецпроэкты: </h1>
        <ul>
          <li>Контент-маркетинг</li>
          <li>Создайте первую игру</li>
          <li>Дзен на дорогах</li>
        </ul>
      <aside>
    </div>
```

**Comment by mkozhukharenko** [comment]
> don't really understand what do you mean. It's already contain it.

Are you sure? 
![image](https://cloud.githubusercontent.com/assets/9365923/15575885/cd0a3238-235d-11e6-98b5-24363eaf6d93.png)

I got 11 'articles'. But there must be 10 or 12.

**Comment by mkozhukharenko** [comment]
> it's not the main navigation

can be a matter of dispute. 
But it's nice that you god you own opinion about that.

**Comment by mkozhukharenko** [comment]
@abatovua please, check you markup here: https://validator.w3.org/
there are a lot of errors 

You were expected to check it before.

**Comment by abatovua** [comment]
> @abatovua please, check you markup here: https://validator.w3.org/
there are a lot of errors

> You were expected to check it before.

Thank you for feedback. i'm gonna fix everything this night :)
